# SPDX-FileCopyrightText: 2025 Eric Berquist <eric.berquist@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-only
[test_config]
engine = "Llvm"
follow-exec = true
skip-clean = true
target-dir = "target/tarpaulin"
